import { Mona_Sans } from "next/font/google";
import "./globals.css";


const monaSans = Mona_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "800"], // choose weights you need
  variable: "--font-mona-sans", // optional: for Tailwind
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
